"""Declared registry of project-owned environment variables."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EnvVar:
    name: str
    required: bool
    secret: bool
    default: str | None
    group: str
    description: str


ENV_VARS: tuple[EnvVar, ...] = (
    EnvVar("LINKEDIN_USERNAME", True, False, None, "credentials",
           "Primary LinkedIn account the daemon runs as."),
    EnvVar("LINKEDIN_PASSWORD", True, True, None, "credentials",
           "Password for the primary LinkedIn account."),
    EnvVar("BACKFILL_LINKEDIN_USERNAME", False, False, None, "credentials",
           "Second LinkedIn account used by backfill_messages and import_connections."),
    EnvVar("BACKFILL_LINKEDIN_PASSWORD", False, True, None, "credentials",
           "Password for the backfill LinkedIn account."),
    EnvVar("SALES_NAV_LINKEDIN_USERNAME", False, False, None, "credentials",
           "LinkedIn account used for Sales Navigator export commands."),
    EnvVar("SALES_NAV_LINKEDIN_PASSWORD", False, True, None, "credentials",
           "Password for the Sales Navigator account."),
    EnvVar("LLM_API_KEY", True, True, None, "llm",
           "API key for the LLM provider; daemon hard-exits without it."),
    EnvVar("AI_MODEL", True, False, None, "llm",
           "LLM model ID used for qualification and synthesis."),
    EnvVar("LLM_API_BASE", False, False, None, "llm",
           "Override base URL for the LLM provider."),
    EnvVar("DATABASE_URL", False, True, None, "database",
           "Postgres connection string; unset falls back to local SQLite."),
    EnvVar("SLACK_WEBHOOK_URL", False, True, None, "slack",
           "Ops webhook for errors, new connections, monitoring, and sweeps."),
    EnvVar("SLACK_REPLIES_WEBHOOK_URL", False, True, None, "slack",
           "Replies webhook for inbound DMs and phone enrichment notices."),
    EnvVar("SLACK_HIGH_SIGNAL_URL", False, True, None, "slack",
           "High-signal webhook for Codex-reviewed LinkedIn and FedRAMP marketplace alerts."),
    EnvVar("SLACK_SIGNING_SECRET", False, True, None, "slack",
           "Signing secret for the Slack enrichment endpoint."),
    EnvVar("SLACK_BOT_TOKEN", False, True, None, "slack",
           "Bot token for Slack modals and message updates."),
    EnvVar("MANUAL_REPLY_POLL_SECONDS", False, False, "60", "slack",
           "Off-hours daemon poll interval for queued Slack manual replies."),
    EnvVar("FEDRAMP_MARKETPLACE_CHANGELOG_URL", False, False,
           "https://raw.githubusercontent.com/FedRAMP/marketplace-fedramp-gov-data/main/fedramp-status-changelog.json",
           "marketplace_listener", "Official FedRAMP status changelog JSON URL."),
    EnvVar("FEDRAMP_MARKETPLACE_DATA_URL", False, False,
           "https://raw.githubusercontent.com/FedRAMP/marketplace-fedramp-gov-data/main/data.json",
           "marketplace_listener", "Official FedRAMP marketplace snapshot JSON URL."),
    EnvVar("FEDRAMP_MARKETPLACE_FETCH_TIMEOUT_SECONDS", False, False, "45",
           "marketplace_listener", "HTTP timeout for each marketplace JSON fetch."),
    EnvVar("GOOGLE_SHEETS_ID", False, False, None, "sheets",
           "Spreadsheet ID for CRM sync; unset disables the sync."),
    EnvVar("GOOGLE_SHEETS_CREDENTIALS_PATH", False, False, None, "sheets",
           "Path to the Sheets service-account JSON key."),
    EnvVar("GOOGLE_SHEETS_TAB_NAME", False, False, "People", "sheets",
           "Worksheet tab name the CRM sync writes to."),
    EnvVar("OUR_COMPANY_NAME", False, False, "", "company",
           "Company name substituted into outbound templates."),
    EnvVar("OUR_WEBSITE_URL", False, False, "", "company",
           "Company URL substituted into outbound templates."),
    EnvVar("BETTERCONTACT_API_KEY", False, True, None, "enrichment",
           "API key for the BetterContact phone-enrichment provider."),
    EnvVar("LEADMAGIC_API_KEY", False, True, None, "enrichment",
           "API key for the LeadMagic phone-enrichment provider."),
    EnvVar("PROSPEO_API_KEY", False, True, None, "enrichment",
           "API key for the Prospeo phone-enrichment provider."),
    EnvVar("ENABLE_CONNECT", False, False, "true", "feature_flags",
           "Enable the connect task lane."),
    EnvVar("ENABLE_SWEEP_CONNECTIONS", False, False, "true", "feature_flags",
           "Enable the bulk connection-sweep task."),
    EnvVar("ENABLE_INCREMENTAL_CONNECTION_SWEEP", False, False, "true", "feature_flags",
           "Use the last successful sender sweep as the bounded Connections cutoff."),
    EnvVar("ENABLE_FOLLOW_UP", False, False, "true", "feature_flags",
           "Enable the post-accept follow-up DM."),
    EnvVar("ENABLE_GMAIL_SEQUENCE", False, False, "false", "feature_flags",
           "Enable post-LinkedIn fallback into email enrichment/Gmail tasks."),
    EnvVar("ENABLE_AUTO_DISCOVERY", False, False, "true", "feature_flags",
           "Enable automatic lead discovery."),
    EnvVar("ENABLE_PROFILE_DISCOVERY", False, False, "false", "feature_flags",
           "Enable bounded profile collection after outbound hours and on rest days."),
    EnvVar("ENABLE_REALTIME_LISTENER", False, False, "false", "feature_flags",
           "Enable the realtime inbound-DM listener child process."),
    EnvVar("ENABLE_LINKEDIN_FEED_COLLECTOR", False, False, "false", "feature_flags",
           "Enable daily LinkedIn home-feed collection from the daemon browser."),
    EnvVar("ENABLE_NODE_MONITOR", False, False, "true", "feature_flags",
           "Enable peer-node liveness and degraded-state monitoring."),
    EnvVar("ENABLE_ACTIVE_HOURS", False, False, "true", "feature_flags",
           "Restrict daemon work to configured active hours."),
    EnvVar("ENABLE_FREEMIUM_CAMPAIGN", False, False, "false", "feature_flags",
           "Enable the freemium campaign path."),
    EnvVar("ENABLE_AUTO_PHONE_ENRICHMENT", False, False, "false", "feature_flags",
           "Auto-enqueue enrichment on every inbound reply."),
    EnvVar("MAX_TOTAL_DAILY_ACTIONS", False, False, "200", "limits",
           "Hard cap on total daemon actions per day."),
    EnvVar("CONNECT_DAILY_LIMIT", False, False, None, "limits",
           "Daily connect-invite cap; unset uses the DB value."),
    EnvVar("CONNECT_WEEKLY_LIMIT", False, False, None, "limits",
           "Weekly connect-invite cap; unset uses the DB value."),
    EnvVar("FOLLOW_UP_DAILY_LIMIT", False, False, None, "limits",
           "Daily follow-up DM cap; unset uses the DB value."),
    EnvVar("CONNECT_LOW_POOL_THRESHOLD", False, False, "100", "limits",
           "Alert when a campaign has this many or fewer connectable leads."),
    EnvVar("CONNECTION_SWEEP_INTERVAL_HOURS", False, False, "2", "limits",
           "Hours between connection sweeps."),
    EnvVar("CONNECTION_SWEEP_OVERLAP_HOURS", False, False, "24", "limits",
           "Overlap before the last successful sweep watermark."),
    EnvVar("CONNECTION_SWEEP_INITIAL_LOOKBACK_DAYS", False, False, "7", "limits",
           "First-run Connections lookback when no successful sweep exists."),
    EnvVar("CONNECTION_SWEEP_MAX_SECONDS", False, False, "180", "limits",
           "Hard browser-runtime budget for one connection sweep."),
    EnvVar("CONNECTION_SWEEP_MAX_ROUNDS", False, False, "120", "limits",
           "Hard scroll-round budget for one connection sweep."),
    EnvVar("CONNECTION_SWEEP_INCOMPLETE_RETRY_MINUTES", False, False, "10", "limits",
           "Retry delay after a sweep exhausts its runtime or round budget."),
    EnvVar("CONNECTION_SWEEP_MAX_QUEUE_DELAY_MINUTES", False, False, "30", "limits",
           "Maximum maintenance-sweep queue delay before it receives fairness priority."),
    EnvVar("TASK_RUNNING_STALE_MINUTES", False, False, "30", "limits",
           "Minimum age before this sender can recover one of its running browser tasks."),
    EnvVar("ACTIVE_START_HOUR", False, False, "9", "schedule",
           "First active hour, inclusive, local time."),
    EnvVar("ACTIVE_END_HOUR", False, False, "17", "schedule",
           "Last active hour, exclusive, local time."),
    EnvVar("ACTIVE_TIMEZONE", False, False, "America/Toronto", "schedule",
           "IANA timezone for active-hours and rest-day calculations."),
    EnvVar("REST_DAYS", False, False, "5,6", "schedule",
           "Comma-separated weekday indices the daemon rests on (Mon=0)."),
    EnvVar("DISCOVERY_DAILY_LIMIT", False, False, "25", "discovery",
           "Maximum new discovery profiles stored per sender/local day."),
    EnvVar("DISCOVERY_MAX_CARDS_PER_RUN", False, False, "200", "discovery",
           "Hard cap on search-result cards scanned in one sender run."),
    EnvVar("DISCOVERY_MAX_PAGES_PER_RUN", False, False, "10", "discovery",
           "Hard cap on People-search pages scanned in one sender run."),
    EnvVar("DISCOVERY_MAX_PROFILE_VISITS_PER_RUN", False, False, "40", "discovery",
           "Hard cap on profiles opened in one sender run."),
    EnvVar("DISCOVERY_MAX_CONSECUTIVE_NO_MATCHES", False, False, "75", "discovery",
           "Stop a sparse run after this many consecutive rejected cards."),
    EnvVar("DISCOVERY_MAX_RUN_MINUTES", False, False, "120", "discovery",
           "Hard wall-clock cap for one sender discovery run."),
    EnvVar("DISCOVERY_PROFILE_DELAY_MIN_SECONDS", False, False, "20", "discovery",
           "Minimum randomized delay between bounded discovery tasks."),
    EnvVar("DISCOVERY_PROFILE_DELAY_MAX_SECONDS", False, False, "45", "discovery",
           "Maximum randomized delay between bounded discovery tasks."),
    EnvVar("LISTENER_CDP_PORT", False, False, "9222", "realtime",
           "Chrome remote-debugging port the listener connects over."),
    EnvVar("LISTENER_CATCHUP_GAP_MINUTES", False, False, "30", "realtime",
           "Off-hours gap the startup catch-up surfaces."),
    EnvVar("LISTENER_PUMP_SLICE_SECONDS", False, False, "30", "realtime",
           "SSE pump slice length in seconds."),
    EnvVar("LISTENER_ACTIVE_START_HOUR", False, False, "0", "realtime",
           "First hour the realtime listener may run, inclusive."),
    EnvVar("LISTENER_ACTIVE_END_HOUR", False, False, "24", "realtime",
           "Last hour the realtime listener may run, exclusive; 24 means midnight."),
    EnvVar("LISTENER_REST_DAYS", False, False, "", "realtime",
           "Comma-separated weekday indices the realtime listener rests on (Mon=0)."),
    EnvVar("LINKEDIN_FEED_COLLECTION_HOUR", False, False, "17", "feed_collection",
           "Local hour when the supervisor should wake daily feed collection."),
    EnvVar("LINKEDIN_FEED_COLLECTION_MINUTE", False, False, "0", "feed_collection",
           "Local minute when the supervisor should wake daily feed collection."),
    EnvVar("LINKEDIN_FEED_COLLECTION_TIMEZONE", False, False, "America/Toronto",
           "feed_collection", "IANA timezone for daily feed collection."),
    EnvVar("LINKEDIN_FEED_COLLECTION_RETRY_MINUTES", False, False, "60",
           "feed_collection", "Retry delay after a feed collection failure."),
    EnvVar("LINKEDIN_FEED_COLLECTION_CUTOFF_OVERLAP_MINUTES", False, False, "1",
           "feed_collection", "Overlap added to the previous collection cutoff."),
    EnvVar("LINKEDIN_FEED_COLLECTION_CATCHUP_DAYS", False, False, "14",
           "feed_collection", "Maximum missed daily feed windows to catch up."),
    EnvVar("LINKEDIN_FEED_COLLECTION_MAX_POSTS", False, False, "1000",
           "feed_collection", "Hard cap on posts extracted per collection run."),
    EnvVar("LINKEDIN_FEED_COLLECTION_STOP_AFTER_SEEN", False, False, "15",
           "feed_collection", "Safety stop after this many already-observed posts."),
    EnvVar("LINKEDIN_FEED_COLLECTION_STOP_AFTER_STALE", False, False, "25",
           "feed_collection", "Safety stop after this many old out-of-window posts."),
    EnvVar("LINKEDIN_FEED_COLLECTION_SCROLL_PAUSE_SECONDS", False, False, "2",
           "feed_collection", "Pause between LinkedIn feed scrolls."),
    EnvVar("LINKEDIN_FEED_COLLECTION_ACTION_DELAY_MIN_SECONDS", False, False, "0.7",
           "feed_collection", "Minimum randomized delay around feed UI actions."),
    EnvVar("LINKEDIN_FEED_COLLECTION_ACTION_DELAY_MAX_SECONDS", False, False, "1.8",
           "feed_collection", "Maximum randomized delay around feed UI actions."),
    EnvVar("ENRICHMENT_MAX_DURATION_SECONDS", False, False, "600", "enrichment_tuning",
           "Max wall-clock duration for one enrichment task."),
    EnvVar("ENRICHMENT_HTTP_TIMEOUT_SECONDS", False, False, "5", "enrichment_tuning",
           "Per-request HTTP timeout for enrichment providers."),
    EnvVar("ENRICHMENT_WAIT_POLL_SECONDS", False, False, "30", "enrichment_tuning",
           "Poll interval while waiting on an enrichment result."),
    EnvVar("BETTERCONTACT_POLL_INTERVAL_SECONDS", False, False, "15", "enrichment_tuning",
           "Poll interval for BetterContact's async job API."),
    EnvVar("MONITOR_INTERVAL_SECONDS", False, False, "300", "monitoring",
           "Heartbeat and scan interval for the node monitor."),
    EnvVar("PEER_STALE_MINUTES", False, False, "15", "monitoring",
           "Peer heartbeat age that marks the peer node down."),
    EnvVar("DEGRADED_REALERT_HOURS", False, False, "6", "monitoring",
           "Cooldown before re-alerting an ongoing outage."),
    EnvVar("TASK_FAILURE_STREAK_THRESHOLD", False, False, "5", "monitoring",
           "Consecutive task failures that trigger a degraded alert."),
    EnvVar("EXPECTED_OUTBOUND_SENDERS", False, False, None, "monitoring",
           "Comma-separated sender handles expected to make outbound progress today."),
    EnvVar("SENDER_ACTIVITY_GRACE_MINUTES", False, False, "60", "monitoring",
           "Minutes after active-day start before expected sender activity is required."),
    EnvVar("SENDER_ACTIVITY_STALE_MINUTES", False, False, "90", "monitoring",
           "Due-work age with no recent ActionLog that marks a fresh sender stuck."),
)
