# Generated by Django 6.0.4 on 2026-08-30 01:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0020_opportunity_active_account_admission'),
        ('linkedin', '0029_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('retired', 'Retired')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='DripCampaignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('manifest', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='drip.dripcampaign')),
            ],
            options={
                'ordering': ('campaign_id', 'version'),
            },
        ),
        migrations.AddField(
            model_name='dripcampaign',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_campaigns', to='drip.dripcampaignversion'),
        ),
        migrations.CreateModel(
            name='DripDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_key', models.CharField(max_length=100)),
                ('theme_index', models.PositiveIntegerField()),
                ('step_index', models.PositiveIntegerField()),
                ('frozen_subject', models.CharField(blank=True, default='', max_length=998)),
                ('frozen_body', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unclear', 'Unclear'), ('stopped', 'Stopped')], db_index=True, default='planned', max_length=16)),
                ('provider_account', models.CharField(max_length=128)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('rfc_message_id', models.CharField(blank=True, default='', max_length=998)),
                ('rfc_references', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drip_delivery', to='linkedin.task')),
                ('outbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drip_deliveries', to='crm.message')),
            ],
            options={
                'ordering': ('lane_id', 'theme_index', 'step_index'),
            },
        ),
        migrations.CreateModel(
            name='DripDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('reserved', 'Reserved'), ('sent', 'Sent'), ('not_submitted', 'Definitely not submitted'), ('unclear', 'Unclear')], default='reserved', max_length=24)),
                ('diagnostic_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='drip.dripdelivery')),
            ],
            options={
                'ordering': ('delivery_id', 'attempt_number'),
            },
        ),
        migrations.CreateModel(
            name='DripEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_icp', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], db_index=True, default='waiting', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=80)),
                ('stop_detail', models.TextField(blank=True, default='')),
                ('enrolled_by', models.CharField(max_length=150)),
                ('plan_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='drip.dripcampaign')),
                ('campaign_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='drip.dripcampaignversion')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drip_enrollments', to='crm.lead')),
                ('stop_trigger_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_drip_enrollments', to='crm.meeting')),
                ('stop_trigger_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_drip_enrollments', to='crm.message')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DripLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('linkedin', 'LinkedIn'), ('gmail', 'Gmail')], max_length=16)),
                ('operator', models.CharField(max_length=64)),
                ('provider_account', models.CharField(max_length=128)),
                ('sender_identity', models.CharField(max_length=254)),
                ('recipient_identity', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('waiting_current', 'Waiting for current sequence'), ('waiting_connection', 'Waiting for connection'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], db_index=True, default='waiting_current', max_length=32)),
                ('current_sequence_status', models.CharField(choices=[('pending', 'Pending review/completion'), ('completed', 'Completed'), ('not_applicable', 'Not applicable')], default='pending', max_length=24)),
                ('current_sequence_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('current_sequence_reviewed_by', models.CharField(blank=True, default='', max_length=150)),
                ('handoff_evidence', models.JSONField(blank=True, default=dict)),
                ('handed_off_at', models.DateTimeField(blank=True, null=True)),
                ('current_theme_index', models.PositiveIntegerField(default=0)),
                ('current_theme_key', models.CharField(blank=True, default='', max_length=100)),
                ('theme_started_at', models.DateTimeField(blank=True, null=True)),
                ('gmail_thread_id', models.CharField(blank=True, default='', max_length=200)),
                ('gmail_thread_subject', models.CharField(blank=True, default='', max_length=998)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lanes', to='drip.dripenrollment')),
            ],
            options={
                'ordering': ('enrollment_id', 'channel'),
            },
        ),
        migrations.AddField(
            model_name='dripdelivery',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='drip.driplane'),
        ),
        migrations.AddConstraint(
            model_name='dripcampaignversion',
            constraint=models.UniqueConstraint(fields=('campaign', 'version'), name='drip_unique_campaign_version'),
        ),
        migrations.AddConstraint(
            model_name='dripcampaignversion',
            constraint=models.UniqueConstraint(fields=('campaign', 'content_hash'), name='drip_unique_campaign_content'),
        ),
        migrations.AddConstraint(
            model_name='dripcampaignversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='drip_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='dripdeliveryattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='drip_unique_delivery_attempt'),
        ),
        migrations.AddConstraint(
            model_name='dripdeliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='drip_attempt_positive'),
        ),
        migrations.AddIndex(
            model_name='dripenrollment',
            index=models.Index(fields=['status', 'created_at'], name='drip_enroll_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='dripenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('waiting', 'active', 'paused'))), fields=('lead',), name='drip_one_open_enrollment'),
        ),
        migrations.AddIndex(
            model_name='driplane',
            index=models.Index(fields=['status', 'channel'], name='drip_lane_status_idx'),
        ),
        migrations.AddIndex(
            model_name='driplane',
            index=models.Index(fields=['channel', 'provider_account', 'recipient_identity'], name='drip_lane_identity_idx'),
        ),
        migrations.AddConstraint(
            model_name='driplane',
            constraint=models.UniqueConstraint(fields=('enrollment', 'channel'), name='drip_one_lane_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='driplane',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('waiting_current', 'waiting_connection', 'active', 'paused')), models.Q(('provider_account', ''), _negated=True), models.Q(('recipient_identity', ''), _negated=True)), fields=('channel', 'provider_account', 'recipient_identity'), name='drip_one_active_recipient_owner'),
        ),
        migrations.AddIndex(
            model_name='dripdelivery',
            index=models.Index(fields=['status', 'scheduled_at'], name='drip_delivery_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='dripdelivery',
            constraint=models.UniqueConstraint(fields=('lane', 'theme_index', 'step_index'), name='drip_unique_lane_step'),
        ),
    ]
