# Generated by Django 6.0.4 on 2026-08-30 19:41

import json
import re
from collections import Counter
from urllib.parse import unquote, urlparse

from django.db import migrations, models


MEMBER_URN_RE = re.compile(r"^urn:li:fsd_profile:[A-Za-z0-9_-]+$")


def _public_id(value):
    if not isinstance(value, str) or not value.strip():
        return ""
    parsed = urlparse(value.strip())
    host = (parsed.hostname or "").strip(".").casefold()
    parts = parsed.path.strip("/").split("/")
    if host not in {"linkedin.com", "www.linkedin.com"} or len(parts) < 2 or parts[0] != "in":
        return ""
    return unquote(parts[1]).strip().casefold()


def _coherent_urn(lead):
    field_public_id = (lead.public_identifier or "").strip().casefold()
    url_public_id = _public_id(lead.linkedin_url)
    if not field_public_id or field_public_id != url_public_id:
        return ""
    try:
        profile = json.loads(lead.description) if lead.description else {}
    except (json.JSONDecodeError, TypeError):
        return ""
    if not isinstance(profile, dict):
        return ""
    profile_public_id = str(profile.get("public_identifier") or "").strip().casefold()
    if profile_public_id != field_public_id or _public_id(profile.get("url")) != field_public_id:
        return ""
    member_urn = str(profile.get("urn") or "").strip()
    return member_urn if MEMBER_URN_RE.fullmatch(member_urn) else ""


def backfill_coherent_linkedin_member_urns(apps, schema_editor):
    Lead = apps.get_model("crm", "Lead")
    DripLane = apps.get_model("drip", "DripLane")
    linkedin_lanes = list(
        DripLane.objects.filter(channel="linkedin").values_list("pk", "enrollment__lead_id"),
    )
    lane_lead_ids = {lead_id for _lane_id, lead_id in linkedin_lanes}
    all_urns_by_lead = {
        lead.pk: _coherent_urn(lead)
        for lead in Lead.objects.all().only(
            "pk",
            "linkedin_url",
            "public_identifier",
            "description",
        )
    }
    urn_by_lead = {
        lead_id: all_urns_by_lead.get(lead_id, "")
        for lead_id in lane_lead_ids
    }
    counts = Counter(urn for urn in all_urns_by_lead.values() if urn)
    for lane_id, lead_id in linkedin_lanes:
        member_urn = urn_by_lead.get(lead_id, "")
        if member_urn and counts[member_urn] == 1:
            DripLane.objects.filter(pk=lane_id).update(linkedin_member_urn=member_urn)


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driplane',
            name='linkedin_member_urn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.RunPython(
            backfill_coherent_linkedin_member_urns,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='driplane',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'linkedin'), ('status__in', ('waiting_current', 'waiting_connection', 'active', 'paused')), models.Q(('linkedin_member_urn', ''), _negated=True)), fields=('linkedin_member_urn',), name='drip_one_active_linkedin_urn'),
        ),
    ]
