# Generated by Django 6.0.4 on 2026-08-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0002_freeze_linkedin_member_urn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DripTrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25, unique=True)),
                ('link_key', models.SlugField(max_length=100)),
                ('destination_url', models.URLField(max_length=2048)),
                ('attributed_url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_links', to='drip.dripdelivery')),
            ],
            options={
                'ordering': ('delivery_id', 'link_key'),
                'constraints': [models.UniqueConstraint(fields=('delivery',), name='drip_one_tracked_link_per_delivery'), models.UniqueConstraint(fields=('delivery', 'link_key'), name='drip_unique_delivery_link_key')],
            },
        ),
    ]
