# Generated by Django 6.0.4 on 2026-08-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drip", "0002_freeze_linkedin_member_urn"),
    ]

    operations = [
        migrations.AddField(
            model_name="dripdelivery",
            name="frozen_media_kind",
            field=models.CharField(
                blank=True,
                choices=[("gif", "GIF"), ("video", "Video")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="dripdelivery",
            name="frozen_media_mime_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="dripdelivery",
            name="frozen_media_reference",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="dripdelivery",
            name="frozen_media_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dripdelivery",
            name="frozen_media_size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
