# Generated by Django 6.0.4 on 2026-04-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_deal_sent_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
