# Generated by Django 6.0.4 on 2026-04-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_deal_last_reply_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attio_company_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='attio_entry_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='attio_person_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
