# Generated by Django 6.0.4 on 2026-04-27 23:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_lead_attio_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('gmail', 'Gmail'), ('calendar', 'Calendar')], max_length=16)),
                ('external_id', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (from lead)'), ('outbound', 'Outbound (from us)')], max_length=16)),
                ('sender', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('thread_external_id', models.CharField(blank=True, default='', max_length=200)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.lead')),
            ],
            options={
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['lead', 'sent_at'], name='crm_message_lead_id_72e6e2_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
