# Generated by Django 6.0.4 on 2026-04-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='last_synthesized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='wants_meeting_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
