# Generated by Django 6.0.4 on 2026-05-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_email_and_synthesis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='airtable_company_record_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='airtable_deal_record_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='airtable_person_record_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
