# Generated by Django 6.0.4 on 2026-05-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_drop_lead_attio_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='connected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
