# Generated by Django 6.0.4 on 2026-05-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_deal_connected_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_calendar', 'Google Calendar')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('gemini_doc_id', models.CharField(blank=True, default='', max_length=255)),
                ('gemini_doc_title', models.CharField(blank=True, default='', max_length=500)),
                ('gemini_notes_raw', models.TextField(blank=True, default='')),
                ('gemini_notes_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='crm.lead')),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['lead', '-start_at'], name='crm_meeting_lead_id_9f7126_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
