# Generated by Django 6.0.4 on 2026-05-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='icp',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
