# Generated by Django 6.0.4 on 2026-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_enriched_at',
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_providers_tried',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='phones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
