# Generated by Django 6.0.4 on 2026-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_lead_email_providers_tried'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='invitation_sender',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='deal',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='invitation_withdrawn_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
