# Generated by Django 6.0.4 on 2026-08-26 05:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


def seed_sales_owners_and_meeting_context(apps, schema_editor):
    """Seed strict owners and copy legacy Meeting context additively."""
    SalesOwner = apps.get_model("crm", "SalesOwner")
    Message = apps.get_model("crm", "Message")
    Meeting = apps.get_model("crm", "Meeting")
    MeetingParticipant = apps.get_model("crm", "MeetingParticipant")
    MeetingNote = apps.get_model("crm", "MeetingNote")

    owners = {}
    for handle in ("Arian", "Chuka", "Athena", "Leili"):
        owner, _created = SalesOwner.objects.get_or_create(
            normalized_handle=handle.casefold(),
            defaults={"handle": handle, "display_name": handle, "active": True},
        )
        owners[handle] = owner

    # Backfill provenance only where one exact, known sender alias identifies
    # an operator.  Unknown/shared sender strings remain null; opportunity
    # ownership is never selected by message volume in this migration.
    message_owner_aliases = {
        "arian": "Arian",
        "arian taj": "Arian",
        "arian tajbakhsh": "Arian",
        "ariantajbakh@gmail.com": "Arian",
        "ariantajbaka@gmail.com": "Arian",
        "ariant2013@gmail.com": "Arian",
        "ariant@tryfedrampgpt.com": "Arian",
        "ariant@boundera.io": "Arian",
        "arian@boundera.io": "Arian",
        "chuka": "Chuka",
        "chuka agu": "Chuka",
        "chukwuka": "Chuka",
        "chukwuka agu": "Chuka",
        "chuka eddy jack": "Chuka",
        "chuky eddy jack": "Chuka",
        "chukyjack@gmail.com": "Chuka",
        "eddy@tryfedrampgpt.com": "Chuka",
        "eddy@boundera.io": "Chuka",
        "athena": "Athena",
        "athena aghdami": "Athena",
        "athenaaghdami": "Athena",
        "athenaaghdami@gmail.com": "Athena",
        "athena@getboundera.com": "Athena",
        "leili": "Leili",
        "leili amirshahi": "Leili",
        "leiliash2011": "Leili",
        "leili.ash2011@yahoo.com": "Leili",
    }
    for alias, handle in message_owner_aliases.items():
        Message.objects.filter(
            direction="outbound",
            operator_id__isnull=True,
            sender__iexact=alias,
        ).update(operator_id=owners[handle].pk)

    meetings = Meeting.objects.select_related("lead").all().iterator(chunk_size=200)
    for meeting in meetings:
        lead = meeting.lead
        MeetingParticipant.objects.get_or_create(
            meeting_id=meeting.pk,
            lead_id=meeting.lead_id,
            defaults={
                "attendee_email": (lead.email or "").strip().casefold(),
                "attendee_name": f"{lead.first_name} {lead.last_name}".strip(),
                "match_method": "legacy_primary",
                "match_evidence": {"migration": "crm.0016"},
                "is_primary": True,
            },
        )

        if not meeting.gemini_notes_raw:
            continue
        external_id = (meeting.gemini_doc_id or "").strip() or f"legacy-meeting:{meeting.pk}"
        if MeetingNote.objects.filter(
            source="gemini",
            external_id=external_id,
        ).exclude(meeting_id=meeting.pk).exists():
            external_id = f"{external_id}:meeting:{meeting.pk}"
        MeetingNote.objects.get_or_create(
            source="gemini",
            external_id=external_id,
            defaults={
                "meeting_id": meeting.pk,
                "title": meeting.gemini_doc_title or meeting.title,
                "calendar_event_id": meeting.external_id,
                "scheduled_start_at": meeting.start_at,
                "scheduled_end_at": meeting.end_at,
                "attendees": meeting.attendees or [],
                "content": meeting.gemini_notes_raw,
                "raw": {
                    "migration": "crm.0016",
                    "legacy_meeting_id": meeting.pk,
                    "gemini_doc_id": meeting.gemini_doc_id,
                },
                "source_created_at": meeting.creation_date,
                "source_updated_at": meeting.update_date,
                "fetched_at": meeting.gemini_notes_fetched_at,
                "detail_status": "complete",
                "match_status": "matched",
                "match_method": "legacy_primary",
                "match_evidence": {
                    "migration": "crm.0016",
                    "lead_id": meeting.lead_id,
                },
                "matcher_version": 1,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_deal_invitation_sender_deal_invitation_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNoteSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('granola', 'Granola'), ('gemini', 'Gemini')], max_length=16, unique=True)),
                ('successful_watermark', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='idle', max_length=16)),
                ('last_error_kind', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=64, unique=True)),
                ('normalized_handle', models.CharField(editable=False, max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['handle'],
            },
        ),
        migrations.AlterField(
            model_name='meeting',
            name='source',
            field=models.CharField(choices=[('google_calendar', 'Google Calendar'), ('granola', 'Granola')], max_length=32),
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('attendee_name', models.CharField(blank=True, default='', max_length=200)),
                ('response_status', models.CharField(blank=True, default='', max_length=40)),
                ('match_method', models.CharField(choices=[('legacy_primary', 'Legacy Primary Lead'), ('attendee_email', 'Attendee Email'), ('attendee_identity', 'Attendee Identity'), ('account_date_title', 'Account + Date + Title'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('match_evidence', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_participations', to='crm.lead')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='crm.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_meetings', through='crm.MeetingParticipant', to='crm.lead'),
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motion_key', models.CharField(default='primary', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('discovery', 'Discovery'), ('demo_planning', 'Demo Planning'), ('evaluation', 'Evaluation'), ('sandbox_pilot', 'Sandbox/Pilot'), ('commercial', 'Commercial'), ('procurement_legal', 'Procurement/Legal'), ('closed_won', 'Closed Won'), ('expansion', 'Expansion'), ('closed_lost', 'Closed Lost')], db_index=True, default='prospecting', max_length=32)),
                ('stage_entered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sales_motion_step', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('last_meaningful_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('manual_pin', models.BooleanField(db_index=True, default=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('closed_won_at', models.DateTimeField(blank=True, null=True)),
                ('closed_lost_at', models.DateTimeField(blank=True, null=True)),
                ('closed_lost_reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sheet', 'Google Sheet'), ('bootstrap', 'Bootstrap'), ('system', 'System')], default='manual', max_length=16)),
                ('human_revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.account')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.salesowner')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('granola', 'Granola'), ('gemini', 'Gemini')], db_index=True, max_length=16)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('web_url', models.URLField(blank=True, default='', max_length=1000)),
                ('calendar_event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('scheduled_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True, default='')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('summary_markdown', models.TextField(blank=True, default='')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('transcript_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('detail_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('retry', 'Retry'), ('unavailable', 'Unavailable')], db_index=True, default='pending', max_length=16)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ambiguous', 'Ambiguous')], db_index=True, default='unmatched', max_length=16)),
                ('match_method', models.CharField(blank=True, choices=[('attendee_email', 'Attendee Email'), ('attendee_identity', 'Attendee Identity'), ('account_date_title', 'Account + Date + Title'), ('existing_event_id', 'Existing Calendar Event ID'), ('legacy_primary', 'Legacy Primary Lead'), ('manual', 'Manual')], default='', max_length=32)),
                ('match_evidence', models.JSONField(blank=True, default=dict)),
                ('matcher_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='crm.meeting')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='crm.opportunity')),
            ],
            options={
                'ordering': ['-scheduled_start_at', '-source_updated_at', 'source', 'external_id'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='crm.opportunity'),
        ),
        migrations.CreateModel(
            name='OpportunityAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('needs_response', 'Needs Response'), ('next_step', 'Next Step'), ('meeting_prep', 'Meeting Preparation'), ('post_meeting_commitment', 'Post-meeting Commitment'), ('followup', 'Follow-up'), ('recovery_review', 'Recovery Review')], default='next_step', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('description', models.TextField()),
                ('due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('waiting_until', models.DateField(blank=True, db_index=True, null=True)),
                ('disposition', models.CharField(blank=True, choices=[('sent', 'Sent'), ('handled', 'Handled'), ('deferred', 'Deferred'), ('polite_decline', 'Polite Decline'), ('no_action', 'No Action')], default='', max_length=24)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='crm.opportunity')),
                ('trigger_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_actions', to='crm.meeting')),
                ('trigger_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_actions', to='crm.message')),
            ],
            options={
                'ordering': ['status', 'due_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('champion', 'Champion'), ('decision_maker', 'Decision Maker'), ('stakeholder', 'Stakeholder'), ('other', 'Other')], default='stakeholder', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_roles', to='crm.lead')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunitySheetState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_human_snapshot', models.JSONField(blank=True, default=dict)),
                ('published_revision', models.PositiveBigIntegerField(default=0)),
                ('published_action_id', models.UUIDField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_state', to='crm.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, default='', max_length=32)),
                ('to_stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('discovery', 'Discovery'), ('demo_planning', 'Demo Planning'), ('evaluation', 'Evaluation'), ('sandbox_pilot', 'Sandbox/Pilot'), ('commercial', 'Commercial'), ('procurement_legal', 'Procurement/Legal'), ('closed_won', 'Closed Won'), ('expansion', 'Expansion'), ('closed_lost', 'Closed Lost')], max_length=32)),
                ('source', models.CharField(choices=[('sheet', 'Google Sheet'), ('manual', 'Manual'), ('bootstrap', 'Bootstrap'), ('system', 'System')], default='system', max_length=16)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='crm.opportunity')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to='crm.salesowner')),
            ],
            options={
                'ordering': ['changed_at', 'created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.salesowner'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lead', 'operator', 'sent_at'], name='crm_message_lead_id_8b3510_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['lead', 'meeting'], name='crm_meeting_part_lead_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'lead'), name='unique_meeting_participant_lead'),
        ),
        migrations.AddIndex(
            model_name='meetingnote',
            index=models.Index(fields=['source', 'source_updated_at'], name='crm_note_source_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingnote',
            index=models.Index(fields=['source', 'match_status'], name='crm_note_source_match_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingnote',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_meeting_note'),
        ),
        migrations.AddConstraint(
            model_name='meetingnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_status', 'matched'), _negated=True), ('meeting__isnull', False), ('opportunity__isnull', False), _connector='OR'), name='matched_note_has_crm_link'),
        ),
        migrations.AddIndex(
            model_name='opportunityaction',
            index=models.Index(fields=['status', 'due_on'], name='crm_action_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityaction',
            index=models.Index(fields=['opportunity', 'status'], name='crm_action_opp_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'waiting'])), fields=('opportunity',), name='one_current_action_per_opportunity'),
        ),
        migrations.AddConstraint(
            model_name='opportunityaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('opportunity', 'idempotency_key'), name='unique_action_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='opportunityaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'waiting'), _negated=True), ('waiting_until__isnull', False), _connector='OR'), name='waiting_action_has_waiting_date'),
        ),
        migrations.AddConstraint(
            model_name='opportunityaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='completed_action_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='opportunitycontact',
            index=models.Index(fields=['opportunity', 'role'], name='crm_opp_contact_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunitycontact',
            constraint=models.UniqueConstraint(fields=('opportunity', 'lead', 'role'), name='unique_opportunity_contact_role'),
        ),
        migrations.AddIndex(
            model_name='opportunitystageevent',
            index=models.Index(fields=['opportunity', '-changed_at'], name='crm_stage_event_opp_time_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner', 'stage'], name='crm_opp_owner_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage', 'last_meaningful_activity_at'], name='crm_opp_stage_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.UniqueConstraint(fields=('account', 'motion_key'), name='unique_opportunity_per_account_motion'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('sales_motion_step__isnull', True), models.Q(('sales_motion_step__gte', 1), ('sales_motion_step__lte', 15)), _connector='OR'), name='opportunity_step_between_1_and_15'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('probability__isnull', True), models.Q(('probability__gte', 0), ('probability__lte', 100)), _connector='OR'), name='opportunity_probability_0_to_100'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('closed_won_at__isnull', True), ('closed_lost_at__isnull', True), _connector='OR'), name='opportunity_not_both_won_and_lost'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'closed_won'), _negated=True), models.Q(('closed_lost_at__isnull', True), ('closed_won_at__isnull', False)), _connector='OR'), name='closed_won_opportunity_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'closed_lost'), _negated=True), models.Q(('closed_lost_at__isnull', False), ('closed_won_at__isnull', True), models.Q(('closed_lost_reason', ''), _negated=True)), _connector='OR'), name='closed_lost_opportunity_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sales_motion_step', 1), ('stage', 'prospecting')), models.Q(('sales_motion_step', 2), ('stage', 'discovery')), models.Q(('sales_motion_step__in', [3, 4]), ('stage', 'demo_planning')), models.Q(('sales_motion_step__in', [5, 6]), ('stage', 'evaluation')), models.Q(('sales_motion_step__in', [7, 8, 9, 10]), ('stage', 'sandbox_pilot')), models.Q(('sales_motion_step', 11), ('stage', 'commercial')), models.Q(('sales_motion_step__in', [12, 13, 14]), ('stage', 'procurement_legal')), models.Q(('sales_motion_step', 15), ('stage', 'expansion')), ('stage__in', ['closed_won', 'closed_lost']), _connector='OR'), name='opportunity_stage_matches_sales_step'),
        ),
        migrations.RunPython(
            seed_sales_owners_and_meeting_context,
            migrations.RunPython.noop,
        ),
    ]
