# Generated by Django 6.0.4 on 2026-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0002_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('operator', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('counts', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['name', 'operator', '-completed_at'], name='linkedin_wo_name_04627b_idx')],
            },
        ),
    ]
