# Generated by Django 6.0.4 on 2026-05-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0003_workflowrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='cookie_data',
        ),
    ]
