# Generated by Django 6.0.4 on 2026-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0006_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaemonHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, unique=True)),
                ('last_alive', models.DateTimeField(blank=True, null=True)),
                ('down_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
