# Generated by Codex on 2026-05-19

from django.db import migrations


FOLLOW_UP_BACKFILL_SQL = r"""
UPDATE linkedin_task AS t
SET payload = jsonb_set(
    COALESCE(t.payload::jsonb, '{}'::jsonb),
    '{operator}',
    to_jsonb(
        CASE lower(btrim(u.username))
            -- auth_user.username values actually in the DB (bare handles).
            WHEN 'chukyjack' THEN 'Chuka'
            WHEN 'ariantajbakh' THEN 'Arian'
            WHEN 'leiliash2011' THEN 'Leili'
            WHEN 'athenaaghdami' THEN 'Athena'
            -- Other known aliases (mirrors linkedin/operators.py).
            WHEN 'chuka' THEN 'Chuka'
            WHEN 'chukwuka' THEN 'Chuka'
            WHEN 'chukwuka agu' THEN 'Chuka'
            WHEN 'chuka eddy jack' THEN 'Chuka'
            WHEN 'chuky eddy jack' THEN 'Chuka'
            WHEN 'chukyjack@gmail.com' THEN 'Chuka'
            WHEN 'eddy@tryfedrampgpt.com' THEN 'Chuka'
            WHEN 'arian' THEN 'Arian'
            WHEN 'arian taj' THEN 'Arian'
            WHEN 'arian tajbakhsh' THEN 'Arian'
            WHEN 'ariantajbakh@gmail.com' THEN 'Arian'
            WHEN 'ariantajbaka@gmail.com' THEN 'Arian'
            WHEN 'ariant2013@gmail.com' THEN 'Arian'
            WHEN 'ariant@tryfedrampgpt.com' THEN 'Arian'
            WHEN 'leili' THEN 'Leili'
            WHEN 'leili.ash2011@yahoo.com' THEN 'Leili'
            WHEN 'athena' THEN 'Athena'
            WHEN 'athenaaghdami@gmail.com' THEN 'Athena'
            ELSE btrim(u.username)
        END
    ),
    true
)
FROM linkedin_campaign AS c
JOIN auth_user AS u
  ON u.id = c.user_id
WHERE t.task_type = 'follow_up'
  AND t.status IN ('pending', 'running')
  AND (NOT (t.payload ? 'operator') OR COALESCE(t.payload->>'operator', '') = '')
  AND COALESCE(t.payload->>'campaign_id', '') ~ '^[0-9]+$'
  AND c.id = (t.payload->>'campaign_id')::int
"""


INVALID_TASK_FAIL_SQL = r"""
UPDATE linkedin_task
SET status = 'failed',
    completed_at = COALESCE(completed_at, NOW()),
    error = trim(both E'\n' from concat_ws(
        E'\n',
        nullif(error, ''),
        '[ownership-hardening 2026-05-19] invalid pending/running task payload'
    ))
WHERE status IN ('pending', 'running')
  AND (
      (
          task_type = 'connect'
          AND COALESCE(payload->>'campaign_id', '') = ''
      )
      OR
      (
          task_type = 'follow_up'
          AND (
              COALESCE(payload->>'campaign_id', '') = ''
              OR COALESCE(payload->>'public_id', '') = ''
              OR COALESCE(payload->>'operator', '') = ''
          )
      )
  )
"""


ADD_CONNECT_CONSTRAINT_SQL = r"""
ALTER TABLE linkedin_task
ADD CONSTRAINT linkedin_task_connect_payload_ck
CHECK (
    status NOT IN ('pending', 'running')
    OR task_type <> 'connect'
    OR COALESCE(payload->>'campaign_id', '') <> ''
)
"""


ADD_FOLLOW_UP_CONSTRAINT_SQL = r"""
ALTER TABLE linkedin_task
ADD CONSTRAINT linkedin_task_follow_up_payload_ck
CHECK (
    status NOT IN ('pending', 'running')
    OR task_type <> 'follow_up'
    OR (
        COALESCE(payload->>'campaign_id', '') <> ''
        AND COALESCE(payload->>'public_id', '') <> ''
        AND COALESCE(payload->>'operator', '') <> ''
    )
)
"""


DROP_CONNECT_CONSTRAINT_SQL = """
ALTER TABLE linkedin_task
DROP CONSTRAINT IF EXISTS linkedin_task_connect_payload_ck
"""


DROP_FOLLOW_UP_CONSTRAINT_SQL = """
ALTER TABLE linkedin_task
DROP CONSTRAINT IF EXISTS linkedin_task_follow_up_payload_ck
"""


def forwards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(FOLLOW_UP_BACKFILL_SQL)
        cursor.execute(INVALID_TASK_FAIL_SQL)
        cursor.execute(ADD_CONNECT_CONSTRAINT_SQL)
        cursor.execute(ADD_FOLLOW_UP_CONSTRAINT_SQL)


def backwards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(DROP_CONNECT_CONSTRAINT_SQL)
        cursor.execute(DROP_FOLLOW_UP_CONSTRAINT_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0007_daemonheartbeat"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
