# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0009_connectissuelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("disabled", "Disabled"),
                    ("finished", "Finished"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
