# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0010_campaign_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachSuppression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("company", "Company"), ("lead", "Lead")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("normalized_value", models.CharField(db_index=True, editable=False, max_length=200)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("normalized_aliases", models.JSONField(blank=True, default=list, editable=False)),
                ("domain", models.CharField(blank=True, db_index=True, default="", max_length=200)),
                ("email", models.EmailField(blank=True, db_index=True, default="", max_length=200)),
                ("linkedin_url", models.URLField(blank=True, db_index=True, default="", max_length=500)),
                ("public_identifier", models.CharField(blank=True, db_index=True, default="", max_length=200)),
                ("reason", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["active", "kind", "normalized_value"], name="linkedin_ou_active_1d460f_idx"),
                    models.Index(fields=["active", "domain"], name="linkedin_ou_active_d26b9b_idx"),
                    models.Index(fields=["active", "email"], name="linkedin_ou_active_e27ce4_idx"),
                    models.Index(fields=["active", "public_identifier"], name="linkedin_ou_active_5c24e8_idx"),
                ],
            },
        ),
    ]
