# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0011_outreachsuppression"),
    ]

    operations = [
        migrations.AddField(
            model_name="daemonheartbeat",
            name="activity_alerted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
