# Generated by Django 6.0.4 on 2026-06-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0014_alter_task_task_type_gmail_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connectissuelog',
            new_name='linkedin_co_linkedi_ffbdbf_idx',
            old_name='linkedin_co_linkedi_114aa0_idx',
        ),
        migrations.RenameIndex(
            model_name='connectissuelog',
            new_name='linkedin_co_public__0bc0ce_idx',
            old_name='linkedin_co_public__4b8c93_idx',
        ),
    ]
