# Generated by Django 6.0.4 on 2026-07-03 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0017_alter_task_task_type_status_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInFeedCollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(db_index=True, max_length=80)),
                ('account_username', models.CharField(db_index=True, max_length=200)),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('posts_seen', models.PositiveIntegerField(default=0)),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('observations_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='linkedin_feed_job_due_idx'), models.Index(fields=['operator', 'account_username', 'collection_date'], name='lfeed_job_sender_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('operator', 'account_username', 'collection_date'), name='linkedin_feed_one_job_per_sender_day')],
            },
        ),
        migrations.CreateModel(
            name='LinkedInFeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_urn', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('post_url', models.URLField(blank=True, default='', max_length=1000)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=200)),
                ('author_headline', models.TextField(blank=True, default='')),
                ('author_profile_url', models.URLField(blank=True, default='', max_length=1000)),
                ('post_text', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen_at'], name='linkedin_feed_post_seen_idx'), models.Index(fields=['author_name'], name='linkedin_feed_post_author_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activity_urn', ''), _negated=True), fields=('activity_urn',), name='linkedin_feed_unique_activity_urn')],
            },
        ),
        migrations.CreateModel(
            name='LinkedInFeedObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(db_index=True, max_length=80)),
                ('account_username', models.CharField(db_index=True, max_length=200)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='linkedin.linkedinfeedcollectionjob')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='linkedin.linkedinfeedpost')),
            ],
            options={
                'indexes': [models.Index(fields=['operator', 'account_username', 'last_seen_at'], name='lfeed_obs_sender_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'operator', 'account_username'), name='linkedin_feed_unique_observation')],
            },
        ),
    ]
