# Generated by Django 6.0.4 on 2026-07-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0018_linkedinfeedcollectionjob_linkedinfeedpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='audience',
            field=models.CharField(blank=True, choices=[('csp', 'CSP'), ('advisor_partner', 'Advisor / Partner'), ('assessor', 'Assessor'), ('channel', 'Channel'), ('other', 'Other'), ('not_relevant', 'Not Relevant')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='intent',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='raw_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='relevance_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='slack_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='suggested_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='linkedinfeedpost',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
