# Generated by Django 6.0.4 on 2026-07-22 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0019_linkedinfeedpost_analyzed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedRAMPMarketplaceSourceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=40, unique=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('source_exported_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('last_polled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FedRAMPMarketplaceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('source_kind', models.CharField(choices=[('changelog', 'Status changelog'), ('snapshot', 'Marketplace snapshot diff')], max_length=20)),
                ('source_event_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('signal_type', models.CharField(choices=[('rev5_ready', 'Rev5 Ready'), ('20x_initial', '20x Initial Implementation')], db_index=True, max_length=30)),
                ('icp_bucket', models.CharField(db_index=True, max_length=64)),
                ('product_id', models.CharField(db_index=True, max_length=80)),
                ('provider_name', models.CharField(db_index=True, max_length=300)),
                ('offering_name', models.CharField(blank=True, default='', max_length=300)),
                ('certification_path', models.CharField(blank=True, default='', max_length=80)),
                ('from_status', models.CharField(blank=True, default='', max_length=100)),
                ('to_status', models.CharField(max_length=100)),
                ('transition_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('marketplace_url', models.URLField(blank=True, default='', max_length=1000)),
                ('product_context', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_relevant', models.BooleanField(db_index=True, default=False)),
                ('should_alert', models.BooleanField(db_index=True, default=False)),
                ('priority', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='', max_length=20)),
                ('relevance_reason', models.TextField(blank=True, default='')),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('slack_notified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['signal_type', 'recorded_at'], name='fedramp_sig_type_rec_idx'), models.Index(fields=['analyzed_at', 'slack_notified_at'], name='fedramp_sig_review_idx')],
            },
        ),
    ]
