# Generated by Django 6.0.4 on 2026-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0020_fedrampmarketplacesourcestate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('withdraw_invite', 'Withdraw Invite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('sweep_connections', 'Sweep Connections'), ('withdraw_invites', 'Withdraw Invites'), ('enrich_phone', 'Enrich Phone'), ('enrich_email', 'Enrich Email'), ('gmail_follow_up', 'Gmail Follow Up'), ('manual_reply', 'Manual Reply'), ('status_summary', 'Status Summary')], max_length=20),
        ),
    ]
