# Generated by Django 6.0.4 on 2026-09-02 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_opportunity_active_account_admission'),
        ('linkedin', '0029_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='MessageProgramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('published_by', models.CharField(max_length=150)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('based_on_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_versions', to='linkedin.messageprogramversion')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='linkedin.messageprogram')),
            ],
            options={
                'ordering': ('program_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='CampaignMessageEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_key', models.CharField(max_length=160)),
                ('operator', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='message_enrollment', to='crm.deal')),
                ('message_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='linkedin.messageprogramversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='active_message_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_campaigns', to='linkedin.messageprogramversion'),
        ),
        migrations.AddConstraint(
            model_name='campaignmessageenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('audience_key', ''), _negated=True), name='linkedin_msg_enrollment_audience_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='campaignmessageenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('operator', ''), _negated=True), name='linkedin_msg_enrollment_operator_nonblank'),
        ),
        migrations.CreateModel(
            name='OutboundDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('linkedin_connect', 'LinkedIn connection'), ('linkedin_followup', 'LinkedIn follow-up'), ('gmail', 'Gmail')], max_length=32)),
                ('step_key', models.CharField(max_length=160)),
                ('step_index', models.PositiveIntegerField()),
                ('variant_key', models.CharField(max_length=160)),
                ('operator', models.CharField(max_length=64)),
                ('scheduled_at', models.DateTimeField()),
                ('frozen_subject', models.CharField(blank=True, default='', max_length=998)),
                ('frozen_body', models.TextField()),
                ('frozen_media', models.JSONField(blank=True, default=list)),
                ('render_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unclear', 'Unclear'), ('stopped', 'Stopped')], db_index=True, default='planned', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='linkedin.campaignmessageenrollment')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_delivery', to='linkedin.task')),
            ],
            options={
                'ordering': ('enrollment_id', 'channel', 'step_index'),
            },
        ),
        migrations.AddConstraint(
            model_name='messageprogramversion',
            constraint=models.UniqueConstraint(fields=('program', 'version'), name='linkedin_unique_msg_program_version'),
        ),
        migrations.AddConstraint(
            model_name='messageprogramversion',
            constraint=models.UniqueConstraint(fields=('program', 'content_hash'), name='linkedin_unique_msg_program_content'),
        ),
        migrations.AddConstraint(
            model_name='messageprogramversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='linkedin_msg_program_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='messageprogramversion',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='linkedin_msg_schema_version_positive'),
        ),
        migrations.AddIndex(
            model_name='outbounddelivery',
            index=models.Index(fields=['status', 'scheduled_at'], name='linkedin_msg_delivery_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='outbounddelivery',
            constraint=models.UniqueConstraint(fields=('enrollment', 'channel', 'step_key'), name='linkedin_unique_msg_delivery_step_key'),
        ),
        migrations.AddConstraint(
            model_name='outbounddelivery',
            constraint=models.UniqueConstraint(fields=('enrollment', 'channel', 'step_index'), name='linkedin_unique_msg_delivery_step_index'),
        ),
        migrations.AddConstraint(
            model_name='outbounddelivery',
            constraint=models.CheckConstraint(condition=models.Q(('step_index__gte', 0)), name='linkedin_msg_delivery_step_nonnegative'),
        ),
    ]
